name: Sandtrace Security Scan

on:
  workflow_dispatch:
  pull_request:
    branches: ['**']
  push:
    branches: [main, master, develop]

jobs:
  sandtrace:
    uses: cc-consulting-nv/.github/.github/workflows/sandtrace-scan.yml@c61427d4d9f833fac039aa8810142cef98089a98
    with:
      sandtrace_cloud_url: ${{ vars.SANDTRACE_CLOUD_URL }}
    secrets:
      SANDTRACE_API_KEY: ${{ secrets.SANDTRACE_API_KEY }}
    permissions:
      actions: read
      contents: read
      security-events: write
