name: Sandtrace Security Scan

on:
  pull_request:
    branches: ['**']
  push:
    branches: [main, master, develop]

jobs:
  sandtrace:
    uses: cc-consulting-nv/.github/.github/workflows/sandtrace-scan.yml@64ba1ad387c05ce7546301e98d75e9b9c15cfc95
    with:
      sandtrace_cloud_url: ${{ vars.SANDTRACE_CLOUD_URL }}
    secrets:
      SANDTRACE_API_KEY: ${{ secrets.SANDTRACE_API_KEY }}
    permissions:
      actions: read
      contents: read
      security-events: write
