name: Sandtrace Security Scan

on:
  pull_request:
    branches: ['**']
  push:
    branches: [main, master, develop]

jobs:
  sandtrace:
    uses: cc-consulting-nv/.github/.github/workflows/sandtrace-scan.yml@main
    permissions:
      contents: read
      security-events: write
